### ISSUE TITLE
StatePass has no validations

### ISSUE THREAD

**Issue by adamgilman** [adamgilman/stairstep#4]
from stairstep import StateChoice, ChoiceRule, ChoiceExpression, StatePass
```
# Create a ChoiceRule, which is composed of choice expression(s)
# This checks to see if the variable $.type is not "Private"
typeNotPrivate = ChoiceRule(operator="Not", snext="Public", conditions=
    ChoiceExpression(operator="StringEquals", variable="$.type", value="Private")
)

# This checks to see if the value of $.value is >=20 or <30
valueInTwenties = ChoiceRule(operator="And", snext="ValueInTwenties", conditions=
    [
        ChoiceExpression(operator="NumericGreaterThanEquals", variable="$.value", value=20),
        ChoiceExpression(operator="NumericLessThan", variable="$.value", value=30)
    ]
)
state = StateChoice(name="ChoiceStateX", choices=[typeNotPrivate,valueInTwenties],default="DefaultState")

default = StatePass(name="DefaultState", end=True)
in_twenties = StatePass(name="ValueInTwenties", end=True)
public = StatePass(name="Public", end=True)

ss.addState(state)
ss.addState(in_twenties)
ss.addState(public)
ss.json()


>>> ss.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dev2/Desktop/WORKING/stairstep/stairstep/base.py", line 100, in json
    return json.dumps( self.export() )
  File "/Users/dev2/Desktop/WORKING/stairstep/stairstep/base.py", line 85, in export
    states[k] = self.states[k].export()
  File "/Users/dev2/Desktop/WORKING/stairstep/stairstep/base.py", line 14, in export
    self.validate()
  File "/Users/dev2/Desktop/WORKING/stairstep/stairstep/base.py", line 9, in validate
    all_validations = self.base_validations + self.validations
AttributeError: 'StatePass' object has no attribute 'validations'
```

**Comment by adamgilman** [comment]
unable to repro
